Initial commit
Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git checkout master
Already on 'master'

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git fetch origin
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 19 (delta 9), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (19/19), 8.59 KiB | 103.00 KiB/s, done.
From https://github.com/Sandeepjagdale2004/Weather_forecast_system
 * [new branch]      main       -> origin/main
   9b93c58..0480c1f  master     -> origin/master
 * [new tag]         v1.0.0     -> v1.0.0

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git merge origin/main
fatal: refusing to merge unrelated histories

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ ^C

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git status
On branch master
nothing to commit, working tree clean

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ ^[[200~git merge origin/main --allow-unrelated-histories
bash: $'\E[200~git': command not found

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git merge origin/main --allow-unreakted-histories
error: unknown option `allow-unreakted-histories'
usage: git merge [<options>] [<commit>...]
   or: git merge --abort
   or: git merge --continue

    -n                    do not show a diffstat at the end of the merge
    --[no-]stat           show a diffstat at the end of the merge
    --[no-]summary        (synonym to --stat)
    --[no-]log[=<n>]      add (at most <n>) entries from shortlog to merge commit message
    --[no-]squash         create a single commit instead of doing a merge
    --[no-]commit         perform a commit if the merge succeeds (default)
    -e, --[no-]edit       edit message before committing
    --[no-]cleanup <mode> how to strip spaces and #comments from message
    --[no-]ff             allow fast-forward (default)
    --ff-only             abort if fast-forward is not possible
    --[no-]rerere-autoupdate
                          update the index with reused conflict resolution if possible
    --[no-]verify-signatures
                          verify that the named commit has a valid GPG signature
    -s, --[no-]strategy <strategy>
                          merge strategy to use
    -X, --[no-]strategy-option <option=value>
                          option for selected merge strategy
    -m, --[no-]message <message>
                          merge commit message (for a non-fast-forward merge)
    -F, --file <path>     read message from file
    --[no-]into-name <name>
                          use <name> instead of the real target
    -v, --[no-]verbose    be more verbose
    -q, --[no-]quiet      be more quiet
    --[no-]abort          abort the current in-progress merge
    --[no-]quit           --abort but leave index and working tree alone
    --[no-]continue       continue the current in-progress merge
    --[no-]allow-unrelated-histories
                          allow merging unrelated histories
    --[no-]progress       force progress reporting
    -S, --[no-]gpg-sign[=<key-id>]
                          GPG sign commit
    --[no-]autostash      automatically stash/stash pop before and after
    --[no-]overwrite-ignore
                          update ignored files (default)
    --[no-]signoff        add a Signed-off-by trailer
    --no-verify           bypass pre-merge-commit and commit-msg hooks
    --verify              opposite of --no-verify

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git merge origin/main --allow-unrelated-histories
Merge made by the 'ort' strategy.
 README.md | 2 ++
 1 file changed, 2 insertions(+)
 create mode 100644 README.md

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ ^C

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git diff HEAD^ HEAD
diff --git a/README.md b/README.md
new file mode 100644
index 0000000..9fdc842
--- /dev/null
+++ b/README.md
@@ -0,0 +1,2 @@
+# Weather_forecast_system
+Website that updates us with the wether today and for next 4 days

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git add README.md

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git commit -m "Updated README.md after merge"
On branch master
nothing to commit, working tree clean

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ git push origin master
To https://github.com/Sandeepjagdale2004/Weather_forecast_system.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Sandeepjagdale2004/Weather_forecast_system.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Sandeep@LAPTOP-EVG5IO5N MINGW64 ~/Downloads/weather-app-main/weather-app-main (master)
$ ^C
Initial commit

~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~                                                                                                       ~
.git/COMMIT_EDITMSG[+] [unix] (11:55 12/10/2024)                                              17,0-1 All